<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType><TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <ServerGarbageCollection>true</ServerGarbageCollection>
  </PropertyGroup>
  <ItemGroup>
    <RuntimeHostConfigurationOption Include="System.GC.ConserveMemory" Value="9" />
    <RuntimeHostConfigurationOption Include="System.GC.HeapCount" Value="1" />
    <RuntimeHostConfigurationOption Include="System.GC.NoAffinitize" Value="true" />
  </ItemGroup>
  <ItemGroup><ProjectReference Include="../PanelDeck.Desktop/PanelDeck.Desktop.csproj" /></ItemGroup>
</Project>
